### ISSUE TITLE
Showing alarm on a map

### ISSUE THREAD

**Issue by LovelyWatermelon** [WestCoast5550/innoTeam#2]
From User Story # 1 (also look at https://github.com/WestCoast5550/innoTeam/issues/2)
As a control room (CR) operator
I want to be alarmed in the case of any unauthorised activity
In order to dispatch the guards in the area

**Comment by gal20040** [comment]
Added pop-up screen with motion detection info and two variants - Reject and Confirm.

**Comment by gal20040** [comment]
Made main screen with the map of the park and a few cameras. Added pictogram at the main screen - camera detected some motion.
